name: Rebase pull requests when main change

on:
  pull_request_target:
    types: [labeled]
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    name: 'Rebase branch on main'

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.TOKEN_REPO_WRITE }}

      - name: 'Rebase all pull requests targeted'
        if: github.event_name == 'push'
        uses: iadvize/actions/rebase-pull-requests@5598823e476f2c2a6c2aa8b13e776708dcb68ec3
        with:
          # we use another token here
          # because an action in a workflow run can't trigger a new workflow run
          # with the GITHUB_TOKEN
          # @see https://help.github.com/en/articles/events-that-trigger-workflows#event-restrictions
          token: ${{ secrets.TOKEN_REPO_WRITE }}
          label: 'Action: keep-rebased'

      - name: 'Rebase the current pull request'
        if: >
          github.event_name == 'pull_request_target'
          && contains(github.event.pull_request.labels.*.name, 'Action: keep-rebased')
        uses: iadvize/actions/rebase-pull-requests@5598823e476f2c2a6c2aa8b13e776708dcb68ec3
        with:
          # we use another token here
          # because an action in a workflow run can't trigger a new workflow run
          # with the GITHUB_TOKEN
          # @see https://help.github.com/en/articles/events-that-trigger-workflows#event-restrictions
          token: ${{ secrets.TOKEN_REPO_WRITE }}
          prNumber: ${{ github.event.pull_request.number }}
          label: 'Action: keep-rebased'
